"""FORGE MCP Server — exposes FORGE tools over stdio transport.

Provides 4 tools for AI coding assistants (Claude Code, Cursor, etc.):
- forge_scan: Run discovery scan on a codebase
- forge_fix: Run full 12-agent remediation pipeline
- forge_report: Read cached report from .artifacts/
- forge_findings: List individual findings from last scan

Usage:
    python -m forge.mcp_server          # stdio transport
    claude mcp add forge -- python -m forge.mcp_server
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from mcp.server.fastmcp import FastMCP

logger = logging.getLogger(__name__)

mcp = FastMCP(
    "forge",
    instructions=(
        "FORGE: AI-powered codebase auditing and remediation engine. "
        "Scans codebases for security, quality, and architecture issues, "
        "then auto-fixes them using 12 specialized AI agents."
    ),
)


def _resolve_path(path: str) -> str:
    """Resolve and validate a repo path."""
    resolved = str(Path(path).resolve())
    if not Path(resolved).is_dir():
        raise ValueError(f"'{path}' is not a directory")
    return resolved


@mcp.tool()
async def forge_scan(path: str, model: str | None = None) -> dict:
    """Run FORGE discovery scan on a codebase.

    Analyzes the codebase for security vulnerabilities, code quality issues,
    and architectural problems. Returns structured findings with severity
    levels and remediation suggestions.

    Typical duration: ~30 seconds. Cost: ~$0.30-0.50.

    Args:
        path: Path to the repository to scan.
        model: Optional model override (e.g. 'anthropic/claude-haiku-4.5').

    Returns:
        ForgeResult dict with findings count, summary, cost, and duration.
    """
    from forge.standalone import run_standalone

    repo_path = _resolve_path(path)

    # mode="discovery" already skips remediation/validation phases in
    # run_standalone (only runs _run_discovery + _run_triage).  dry_run=True
    # is a safety belt — run_standalone gates remediation on
    # `cfg.mode in (FULL, REMEDIATION) and not cfg.dry_run`, so both flags
    # must be wrong for fixes to be applied accidentally.
    config: dict = {
        "mode": "discovery",
        "dry_run": True,
        "repo_path": repo_path,
    }
    if model:
        config["models"] = {"default": model}

    result = await run_standalone(repo_path=repo_path, config=config)
    return result.model_dump(mode="json")


@mcp.tool()
async def forge_fix(
    path: str,
    model: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Run full FORGE remediation pipeline (12 agents).

    Scans, triages, fixes, and validates the codebase. Fixes are applied
    in isolated git worktrees and merged back on success.

    WARNING: This takes ~25-30 minutes and costs ~$2-5. Use forge_scan
    first to preview findings before committing to full remediation.

    Args:
        path: Path to the repository to fix.
        model: Optional model override for all agents.
        dry_run: If True, scan and plan but don't apply fixes.

    Returns:
        ForgeResult dict with findings fixed, PR URL, cost, and duration.
    """
    from forge.standalone import run_standalone

    repo_path = _resolve_path(path)

    config: dict = {
        "mode": "full",
        "dry_run": dry_run,
        "repo_path": repo_path,
    }
    if model:
        config["models"] = {"default": model}

    result = await run_standalone(repo_path=repo_path, config=config)
    return result.model_dump(mode="json")


@mcp.tool()
def forge_report(path: str) -> dict:
    """Read the cached FORGE report from .artifacts/ directory.

    Returns the most recent discovery report generated by a previous
    forge_scan or forge_fix run. No API calls are made.

    Args:
        path: Path to the repository (must have .artifacts/report/).

    Returns:
        The discovery report as a dict, or an error dict if not found.
    """
    repo_path = _resolve_path(path)
    report_dir = Path(repo_path, ".artifacts", "report")

    if not report_dir.is_dir():
        return {"error": "No report found. Run forge_scan first."}

    # Find the most recent report file
    report_files = sorted(
        report_dir.glob("*.json"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not report_files:
        return {"error": "No report files found in .artifacts/report/."}

    try:
        return json.loads(report_files[0].read_text())
    except (json.JSONDecodeError, OSError) as e:
        return {"error": f"Failed to read report: {e}"}


@mcp.tool()
def forge_status(path: str) -> dict:
    """Get real-time status of a running FORGE scan including cost, time, and agent activity.

    Reads the live_status.json file written by RunTelemetry after every LLM call.
    No API calls are made — this reads a local file that is updated in real-time.

    Args:
        path: Path to the repository being scanned.

    Returns:
        Status dict with cost, time, phase, findings progress, and active agents.
        Returns {"status": "no_active_run"} if no scan is in progress.
    """
    status_file = Path(path) / ".artifacts" / "telemetry" / "live_status.json"
    if not status_file.exists():
        return {"status": "no_active_run"}
    try:
        return json.loads(status_file.read_text())
    except (json.JSONDecodeError, OSError):
        return {"status": "error", "detail": "Failed to read live_status.json"}


@mcp.tool()
def forge_findings(path: str) -> list[dict]:
    """List individual findings from the most recent scan.

    Reads cached scan artifacts. Each finding includes severity, category,
    affected files, and suggested remediation. No API calls are made.

    Args:
        path: Path to the repository (must have .artifacts/scan/).

    Returns:
        List of finding dicts, or a list with a single error dict.
    """
    repo_path = _resolve_path(path)
    scan_dir = Path(repo_path, ".artifacts", "scan")

    if not scan_dir.is_dir():
        return [{"error": "No scan artifacts found. Run forge_scan first."}]

    findings: list[dict] = []
    for f in sorted(scan_dir.glob("*.json")):
        try:
            data = json.loads(f.read_text())
            if isinstance(data, list):
                findings.extend(data)
            elif isinstance(data, dict):
                # Single finding or wrapped findings
                if "findings" in data:
                    findings.extend(data["findings"])
                else:
                    findings.append(data)
        except (json.JSONDecodeError, OSError):
            continue

    if not findings:
        return [{"error": "No findings found in .artifacts/scan/."}]

    return findings


def main() -> None:
    """Entry point for the FORGE MCP server."""
    mcp.run()


if __name__ == "__main__":
    main()
